<?php

namespace app\home\controller;

use app\common\model\Goods;
use app\common\model\Subgoods;
use think\Controller;
use app\common\model\Category;
use think\Session;

class Product extends Controller
{
    private $categoryData;
    private $model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 调取分类数据
        // 获取后台分类表数据
        $model = new Category();
        $this->categoryData = $model->where('pid',0)->select();
        $this->model = new Goods();
    }

    public function goods(){
        $gid = input('gid');
        // 获取商品数据
        $goodsData = $this->model->get($gid);
        //点击数加一
        $this->model->where('gid',$gid)->update(['click'=>$goodsData['click']+1]);
        // 查询货品属性数据
        $subGoodsData = Subgoods::where('goods_id',$gid)->select();

        $totalNum = 0;
        foreach ($subGoodsData as $v){
            $totalNum += $v['snum'];
        }

        $subGoodsData = json_encode($subGoodsData,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);


        // 获取商品图集
        $images = $goodsData['atlas'];
        $images = explode('|',$images);

        // 获取后台分类顶级分类表数据
        // select 选择数据集
        $categoryData = $this->categoryData;

        // 获取购物车数据
        $goods = Session::get('cart.goods');
        if(!is_null($goods)){
            foreach ($goods as $k=>$v){
                // $info = Goods::get($v['id'])->toArray();
                $cover = Goods::where('gid',$v['id'])->value('cover');
                $goods[$k]['cover'] = $cover;
            }
        }
        $cart = json_encode($goods,JSON_UNESCAPED_UNICODE| JSON_UNESCAPED_SLASHES);
        return view('',compact('goodsData','categoryData','images','subGoodsData','totalNum','cart'));
    }
}
